language: node_js
node_js:
  - "6"   # test backwards compatibility
  - node  # latest stable

before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build

before_deploy:
  # create zipfile for release
  - zip modelleertaal-$TRAVIS_TAG.zip index.html config.js scripts/* modellen/*
  # create folder to deploy to gh-pages
  - mkdir _build
  - cp index.html _build/
  - cp config.js _build/
  - cp -R scripts _build/
  - cp -R modellen _build/
  - touch _build/.nojekyll

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _build
    keep_history: true
    local_dir: public
    repo: tomkooij/modelleertaal-dev
    target_branch: master
    verbose: true
    on:
      branch: master
      node_js: node
  - provider: releases
    file:
      - modelleertaal-$TRAVIS_TAG.zip
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    on:
      branch: master
      node_js: node
      tags: true
